### ISSUE TITLE
create_overlay() takes 0 positional arguments but 2 were given

### ISSUE THREAD

**Issue by FJGEODEV** [JintaoLee-Roger/cigvis#2]
Hi, thanks for the great work, got some error. 

I was trying to run overlapped display like: https://cigvis.readthedocs.io/en/latest/gallery/3Dvispy/02-overlay_fault.html

But it shows "create_overlay() takes 0 positional arguments but 2 were given", my input data and mask are all 3D numpy array.

Thanks.

**Comment by FJGEODEV** [comment]
Also tried your shared dataset, seis_h360x600x400.dat and label_h360x600x400.dat, create_overlay()  and plot3D() do not work with arguments.

**Comment by JintaoLee-Roger** [comment]
Can you show your code?

**Comment by FJGEODEV** [comment]
Hi, I followed the exact workflow you shared in this page: https://cigvis.readthedocs.io/en/latest/gallery/3Dvispy/02-overlay_fault.html#sphx-glr-gallery-3dvispy-02-overlay-fault-py

**Comment by JintaoLee-Roger** [comment]
Well, I run the code on my computer, it works fine. 

Can you paste up the information of the error？It will help me to solve the problem.

**Comment by FJGEODEV** [comment]
![image](https://github.com/JintaoLee-Roger/cigvis/assets/42128104/4b1e0396-0e13-439f-b293-b78309971d42)
See this image. Still can't run it.

**Comment by JintaoLee-Roger** [comment]
I guess you are running this in a Jupyter environment. Currently, for 3D plotting, cigvis has only implemented a version based on vispy, so it can only be run in a local environment (as it requires OpenGL, in a Jupyter environment, you should use tools similar to webGL). Support for Jupyter environments will be implemented in the future, but the current support is very limited. Since you are running this in a Jupyter environment, you encountered this error due to the call to `plotlyplot.create_overlay(**kwargs)` instead of `vispyplot.create_overlay()`.

The solution is run the code in terminal instead of jupyter notebook.

**Comment by FJGEODEV** [comment]
Ah OK, I will try, thanks!

**Comment by FJGEODEV** [comment]
I got it, thanks. Python script works!
